export const heading = [
    "Feature",
    "passed",
    "failed",
    "skipped",
    "pending",
    "undefined",
    "total",
];
export const rows = [
    {
        feature: "Manadatory field validation of addAbstract Page",
        passed: 19,
        Failed: 1,
        skipped: 10,
        pending: 0,
        Undefined: 0,
        Total: 100,
    },
    {
        feature: "Navigate to all introduction page",
        passed: 13,
        Failed: 0,
        skipped: 22,
        pending: 44,
        Undefined: 0,
        Total: 13,
    },
    {
        feature: "Manadatory field validation of login page",
        passed: 30,
        Failed: 0,
        skipped: 0,
        pending: 0,
        Undefined: 0,
        Total: 30,
    },
    {
        feature: "Manadatory field validation of Contact Page",
        passed: 100,
        Failed: 0,
        skipped: 0,
        pending: 0,
        Undefined: 0,
        Total: 100,
    },
    {
        feature: "Manadatory field validation of Profile Page",
        passed: 71,
        Failed: 1,
        skipped: 2,
        pending: 0,
        Undefined: 0,
        Total: 74,
    },
];